# Generated by Django 5.2.5 on 2025-08-29 11:01

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0001_initial"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name": "Пост", "verbose_name_plural": "Посты"},
        ),
        migrations.RemoveField(
            model_name="post",
            name="tag",
        ),
        migrations.AddField(
            model_name="post",
            name="tag",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
